<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

</body>
<script>
    // Exercise 1
    // function loadScript(src) {
    //     return new Promise((resolve, reject) => {
    //         let script = document.createElement("script");
    //         script.src = src;
    //         document.body.appendChild(script);
    //         script.onload = function () {
    //             resolve("Script loaded successfully !");
    //         }
    //         script.onerror = function () {
    //             reject(new Error("Script was not loaded"));
    //         }
    //     });
    // }
    // const p1 = loadScript("https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js")
    // p1.then(value => {
    //     console.log(value);
    // }).catch(error => {
    //     console.log(error);
    // })

    // Exercise 2
    // async function loadScript(src) {
    //     return new Promise((resolve, reject) => {
    //         let script = document.createElement("script");
    //         script.src = src;
    //         document.body.appendChild(script);
    //         script.onload = function () {
    //             resolve("Script loaded successfully!");
    //         };
    //         script.onerror = function () {
    //             reject(new Error("Script was not loaded"));
    //         };
    //     });
    // }

    // async function main1() {
    //     try {
    //         const result = await loadScript("https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js");
    //         console.log(result);
    //     } catch (error) {

    //         console.log(error);
    //     }
    // }

    // main1();

    // Exercise 3
    // function getError() {
    //     return new Promise((resolve, reject) => {
    //         setTimeout(() => {
    //             reject(new Error("This is an error.."));
    //         }, 3000)
    //     });
    // }

    // async function main2() {
    //     try {
    //         const c = await getError();
    //         console.log(c);
    //     } catch (error) {
    //         console.log(error);
    //     }
    // }

    // main2();

    // Exercise 4
    let p1 = () => {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                console.log("Task 1 completed");
                resolve(1);
            }, 1000)
        });
    }

    let p2 = () => {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                console.log("Task 2 completed");
                resolve(2);
            }, 2000)
        });
    }

    let p3 = () => {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                console.log("Task 3 completed");
                resolve(3);
            }, 3000)
        });
    }

    async function main3() {
        try {
            const promise_all = await Promise.all([p1(), p2(), p3()]);
            console.log(promise_all);
        } catch (error) {
            console.log("There was some error")
        }
    }

    main3();

</script>

</html>